[package]
name = "calculator-rest"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
actix-web = "4"
log = "0.4.0"
env_logger = "0.9.0"